name             'linux'
maintainer       'Yamashita, Yuu'
maintainer_email 'yuu@treasure-data.com'
license          'Apache 2.0'
description      'Configures Linux kernel parameters'
long_description 'Configures Linux kernel parameters'
version          '0.1.1'
